### PR TITLE
add dashboard

### PR DESCRIPTION
**Pull request by meomancer**
- Add dashboard page
- Create template for wms layer and it's filter so we can reuse to new layer
- Able to filter using cql

Selection_060

Filtered by industrial with canal
Selection_061

### CODE REVIEW

**Comment by meomancer** [comment]
TODO:
- Add road layer
- It is pointing to local geoserver, needs to point to remote geoserver

- Filter list is not from RESTfull API yet (Need API from server)
- Add upload shapefile flood (Need API from server)
- Add vurnerable buildings filters (Need API from server)
- Kartoza branding at footer

**Comment by meomancer** [comment]
Updates:
- add road layers
- filters is using API, but it is predefined by fetching from postgres, the problem is because getting list from osm_buildings is taking a lot of time
- posgrest can't do distinct so needs these to be added to database : https://github.com/kartoza/fbf-project/pull/24/files?file-filters%5B%5D=.py#diff-3233da1767328a676bd41b08839eac23

> -- for statistic and filtering
> -- count number or buildings
> CREATE VIEW osm_buildings_stats as
> SELECT building_type as type, COUNT (building_type)
> FROM osm_buildings
> GROUP BY building_type;

> -- count number or roads
> CREATE VIEW osm_roads_stats as
> SELECT a.type as type, COUNT (a.type)
> FROM osm_roads as a
> GROUP BY a.type;

> -- count number or waterways
> CREATE VIEW osm_waterways_stats as
> SELECT waterway as type, COUNT (waterway)
> FROM osm_waterways
> GROUP BY waterway;

Selection_067
Selection_068

**Comment by timlinux** [comment]
Coming on nicely @meomancer !

**Comment by meomancer** [comment]
Updated: 
- add leaflet draw to clip using cql
Selection_073

**Comment by lucernae** [comment]
Thanks, @meomancer.
Can you add README to set up this project?

**Comment by meomancer** [comment]
hi @timlinux @NyakudyaA 
PR updated:
Now we can filter by polygon and also the count too

but needs this to be implemented:
[fbf.zip](https://github.com/kartoza/fbf-project/files/3812479/fbf.zip)

Here is the demo:
https://drive.google.com/file/d/1zQLFORds_f3lSqSUF0I8Mc33rR7nmAg7/view?usp=sharing

**Pull request merged**
